name: Check Code formatting

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install flake8
          pip --version
        shell: bash
      - name: PEP8
        run: |
          flake8 .

  imports-check-isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install isort
        run: |
          pip install isort==5.6.4
          pip --version
      - name: isort
        run: isort --settings-path=./pyproject.toml --check-only .

  typing-check-mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install mypy
        run: |
          pip install mypy
          pip list
      - name: mypy
        run: |
          mypy
